dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- python manage.py test census
deploy:
  provider: heroku
  app: examen-egc-final-septiembre20
  strategy: git
  api_key:
    secure: ccb1yAvdl5a8O+0mk3JcQC4ZAPYd3hmFfR51hNQf7kToZOPZ/HOq0h0TKw6oGRgaLtoU+HQWGBqmdSPyC6qdYdWSHoli2rThMViw2kRxfCO4eim4nXdjUzHhqkUjNpC9c1WcSXBRLSwaT7NtBYP3I7JfBvmGKyfO9YSQRWLV2dLbmpCuXER3jKBbPLqlGAmMb45ohaBC636Z9HiAB4EUMhFl3jGTSkRHHEHGX4D6UvN7e1MC51Q77N/gqaJ/bXUxORkn3YhVQ+G6FtrZ2RTbcX4V1PauU5HcW8VIhKFtyYbX++yqW58rzEsnG2uKt1M+K5c+js1qyuv+iQKl8I64ex79Ii8NeP9ssXjyOZwDjgxb2Oi7/oukrj74gUrUnQ8iXmMsSusqq/cbLX/5NDnAuOu0Z0m2ryMD5mdFKUzsxsFK0unBcCOUlq6O5xwbY4zwa8uvow4VytefA7F6lx3NsGUBNloGkEuPei4NWsyi5Y/Lr6qmjsfrkm70oxwbGlSpTcpeQODXB751ChEoqEwGrY9W/sqk5inxhZZyvjEtU0X1EZroDaP/V79SxWux40VX6qToJjZ5f7WZoz0/k8+LEwCAP3a/ACGmH12m0EXqSYbOKc6liSCfU5VZXmhzwtoh7qu7wMUYADdh/uwSprgO6r9C8iDZZ7FsY6aLrpSmmRY=
notifications:
  email:
  - frasanmat1@alum.us.es
